### ISSUE TITLE
Add support for long parameters

### ISSUE THREAD

**Issue by cj525** [dswisher/yaclops#1]
EX: -h | --help.

**Comment by dswisher** [comment]
The long name for a parameter is built from the name of the parameter. For your example, the following should work:

    [CommandLineOption(ShortName = "h")]
    public bool Help { get; set; }

That may have been added after the 0.2.0 nuget package was created, so it may not (yet) work for you, but would that satisfy your desire? Or are you seeking a way to override the default long name?

**Comment by cj525** [comment]
An override would be nice because "--add-user" is a common pattern, and matching this pattern with decameling may not be sufficient if the in-code name should be exposed differently for some reason.

**Comment by dswisher** [comment]
This was fixed in the 0.4.0 release.
