### ISSUE TITLE
Help command is implicit, unaliases but not shown in command list.

### ISSUE THREAD

**Issue by cj525** [dswisher/yaclops#4]
Help should (maybe) be it's own ISubCommand class support if it can be implicitly included.  Perhaps registering the YACLOPS assembly provides this, and then adds it to the usage output?

**Comment by dswisher** [comment]
I'm using `git` as my model, and it does not include `help` in the list of subcommands. It *does* include it in a note at the bottom of the main help screen, and I've added that (will be in the 0.5.0 build).

`git` does list `--help` in the usage synopsis, and that should be included when issue #5 is resolved.
