### ISSUE TITLE
Support for aliasing help option to a command

### ISSUE THREAD

**Issue by cj525** [dswisher/yaclops#5]
`myapp help mycmd` should be equivalent to `myapp mycmd --help`, as well as the superfluous help switches: `/?` and `-h`

there may a use-case for supporting this outside of "help", but I can't think of it atm

**Comment by dswisher** [comment]
`myapp --help mycmd` should also work (future tense - it does not yet work).

**Comment by dswisher** [comment]
This seems to be done, except for windows-style switches, which I've moved to its own issue (#15).
